# keys for this dictionary are either WillowAIPawn.AIClass.Name or WillowAIPawn.BalanceDefinitionState.BalanceDefinition.Name
enemy_class_to_loc_name = {
    "CharClass_PrimalBeast_KnuckleDragger":                                      "Enemy: Knuckle Dragger",
    "CharClass_PrimalBeast_Wamong":                                              "Enemy: Midgemong",
    "CharClass_BoomBoom":                                                        "Enemy: Boom",
    "CharClass_Boom":                                                            "Enemy: Bewm",
    "CharClass_Flynt":                                                           "Enemy: Captain Flynt",
    "CharClass_SavageLee":                                                       "Enemy: Savage Lee",
    "CharClass_Boll":                                                            "Enemy: Boll",
    "CharClass_MrMercy":                                                         "Enemy: Doc Mercy",
    "CharClass_Assassin2":                                                       "Enemy: Assassin Oney",
    "CharClass_Assassin1":                                                       "Enemy: Assassin Wot",
    "CharClass_Assassin3":                                                       "Enemy: Assassin Reeth",
    "CharClass_Assassin4":                                                       "Enemy: Assassin Rouf",
    "CharClass_SpiderantScorch":                                                 "Enemy: Scorch",
    "CharClass_IncineratorVanya_Combat":                                         "Enemy: Incinerator Clayton",
    "CharClass_Gettle":                                                          "Enemy: Gettle",
    "CharClass_Mobley":                                                          "Enemy: Mobley",
    "CharClass_BlackQueen":                                                      "Enemy: Black Queen",
    "CharClass_NomadNamed_1":                                                    "Enemy: Bad Maw",
    "PawnBalance_MadMike":                                                       "Enemy: Mad Mike",
    "CharClass_ConstructorRoland":                                               "Enemy: W4R-D3N",
    "CharClass_MonsterMash1":                                                    "Enemy: Spycho",
    "CharClass_McNally":                                                         "Enemy: McNally",
    "CharClass_MickZaford_Combat":                                               "Enemy: Mick/Tector",
    "CharClass_TectorHodunk_Combat":                                             "Enemy: Mick/Tector",
    "CharClass_Rat_Dan":                                                         "Enemy: Dan (Splinter Group)",
    "CharClass_Rat_Lee":                                                         "Enemy: Lee (Splinter Group)",
    "CharClass_Rat_Mick":                                                        "Enemy: Mick (Splinter Group)",
    "CharClass_Rat_Ralph":                                                       "Enemy: Ralph (Splinter Group)",
    "CharClass_RatEasterEgg":                                                    "Enemy: Flinter (Splinter Group)",
    "CharClass_Bugmorph_SirReginald":                                            "Enemy: Madame Von Bartlesby",
    "PawnBalance_Prospector":                                                    "Enemy: Prospector Zeke",
    "CharClass_Willhelm":                                                        "Enemy: Wilhelm",
    "CharClass_Laney":                                                           "Enemy: Laney White",
    "CharClass_RakkMan":                                                         "Enemy: Rakkman",
    "CharClass_BluntCrack":                                                      "Enemy: SmashHead",
    "CharClass_Midget_SwallowedWhole":                                           "Enemy: Shorty",
    "CharClass_Stalker_SwallowedWhole":                                          "Enemy: Sinkhole",
    "PawnBalance_LaneyDwarf1":                                                   "Enemy: Sleazy (Laney Midget)",
    "PawnBalance_LaneyDwarf2":                                                   "Enemy: Dirty (Laney Midget)",
    "PawnBalance_LaneyDwarf3":                                                   "Enemy: Tipsy (Laney Midget)",
    "PawnBalance_LaneyDwarf4":                                                   "Enemy: Crabby (Laney Midget)",
    "PawnBalance_LaneyDwarf5":                                                   "Enemy: Greedy (Laney Midget)",
    "PawnBalance_LaneyDwarf6":                                                   "Enemy: Bloody (Laney Midget)",
    "PawnBalance_LaneyDwarf7":                                                   "Enemy: Creepy (Laney Midget)",
    "CharClass_ThresherSlappy":                                                  "Enemy: Old Slappy",
    "CharClass_ThresherGluttonous":                                              "Enemy: Gluttonous Thresher",
    "CharClass_Stalker_Name1":                                                   "Enemy: Henry",
    "CharClass_Leprechaun":                                                      "Enemy: Bagman",
    "PawnBalance_Blue":                                                          "Enemy: Blue",
    "CharClass_CreeperBadass":                                                   "Enemy: Badass Creeper",
    "CharClass_SkagPair":                                                        "Enemy: Tumbaa",
    "CharClass_StalkerPair":                                                     "Enemy: Pimon",
    "CharClass_NamedRakk1":                                                      "Enemy: Son of Mothrakk",
    # "GD_BloodwingNew.Character.CharClass_Bloodwing":                           "Enemy: Bloodwing",
    "PawnBalance_GoliathSnow": { 5:                                              "Enemy: GOD-liath" }, # unrealsdk.find_enum("EAITransformed")["EAIT_Slagged"] == 5
    "PawnBalance_InfectedGoliath": { 5:                                          "Enemy: GOD-liath" },
    "PawnBalance_Infected_Badass_Goliath": { 5:                                  "Enemy: GOD-liath" },
    "PawnBalance_Infected_Gargantuan_Goliath": { 5:                              "Enemy: GOD-liath" },
    "PawnBalance_GoliathBossProxy": { 5:                                         "Enemy: GOD-liath" },
    "PawnBalance_GoliathBossProxy_Raid": { 5:                                    "Enemy: GOD-liath" },
    "PawnBalance_GoliathBride": { 5:                                             "Enemy: GOD-liath" },
    "PawnBalance_GoliathBrideRaid": { 5:                                         "Enemy: GOD-liath" },
    "PawnBalance_GoliathGroom": { 5:                                             "Enemy: GOD-liath" },
    "PawnBalance_GoliathGroomRaid": { 5:                                         "Enemy: GOD-liath" },
    "Iris_PawnBalance_ArenaGoliath": { 5:                                        "Enemy: GOD-liath" },
    "PawnBalance_BrideNPC": { 5:                                                 "Enemy: GOD-liath" },
    "PawnBalance_GroomNPC": { 5:                                                 "Enemy: GOD-liath" },
    "PawnBalance_Goliath": { 5:                                                  "Enemy: GOD-liath" },
    "PawnBalance_GoliathBadass": { 5:                                            "Enemy: GOD-liath" },
    "PawnBalance_GoliathBlaster": { 5:                                           "Enemy: GOD-liath" },
    "PawnBalance_GoliathCorrosive": { 5:                                         "Enemy: GOD-liath" },
    "PawnBalance_GoliathLootGoon": { 5:                                          "Enemy: GOD-liath" },
    "PawnBalance_DiggerGoliath": { 5:                                            "Enemy: GOD-liath" },
    "PawnBalance_LootMidget_Goliath": { 5:                                       "Enemy: GOD-liath" },
    "CharClass_SarcasticSlab":                                                   "Enemy: Sarcastic Slab",
    "CharClass_Shootyface":                                                      "Enemy: Face McShooty",
    "CharClass_Skagzilla":                                                       "Enemy: Dukino's Mom",
    "CharClass_MadDog":                                                          "Enemy: Mad Dog",
    "CharClass_Sheriff":                                                         "Enemy: Sheriff Nisha",
    "CharClass_Deputy":                                                          "Enemy: Deputy Winger",
    "CharClass_Engineer_Foreman":                                                "Enemy: Foreman Jasper",
    "CharClass_JacksBodyDouble":                                                 "Enemy: Jack's Body Double",
    # "" :                                                                       "Enemy: BNK-3R",
    "CharClass_PrimalBeast_KONG":                                                "Enemy: King Mong",
    "CharClass_PrimalBeast_DonkeyMong":                                          "Enemy: Donkey Mong",
    "CharClass_Mortar":                                                          "Enemy: Mortar",
    "CharClass_Engineer_DJHyperion":                                             "Enemy: Hunter Hellquist",
    "CharClass_BoneHead2":                                                       "Enemy: Bone Head 2.0",
    "PawnBalance_LoaderGiant":                                                   "Enemy: Saturn",
    # "" :                                                                       "Enemy: Warrior",
    "CharClass_Thresher_Raid":                                                   "Enemy: Terramorphous the Invincible",
    # "CharClass_DyingJack":                                                     "Enemy: Dying Handsome Jack",

    "CharClass_Spycho":                                                          "Enemy: Sully the Blacksmith",
    "PawnBalance_FlyingPumpkinhead":                                             "Enemy: Pumpkin Kingpin",
    "PawnBalance_FlyingPumpkinhead_Run":                                         "Enemy: Jacques O'Lantern",
    "CharClass_UndeadFirePsycho_Giant":                                          "Enemy: Cryptkeeper Clark",
    "CharClass_ButcherBoss":                                                     "Enemy: Chef Gouda Remsay",
    "CharClass_RatChef":                                                         "Enemy: The Rat in the Hat",
    "CharClass_ButcherBoss2":                                                    "Enemy: Chef Brulee",
    "CharClass_ButcherBoss3":                                                    "Enemy: Chef Bork Bork",
    "CharClass_BigBird":                                                         "Enemy: Wattle Gobbler",
    "CharClass_SandMale":                                                        "Enemy: Glasspool, Tribute of Wurmwater",
    "CharClass_SandFemale":                                                      "Enemy: William, Tribute of Wurmwater",
    "CharClass_EngineerMale":                                                    "Enemy: Axel, Tribute of Opportunity",
    "CharClass_EngineeFemale":                                                   "Enemy: Rose, Tribute of Opportunity",
    "CharClass_FleshripperFemale":                                               "Enemy: Strip, Tribute of Southern Shelf",
    "CharClass_FleshripperMale":                                                 "Enemy: Flay, Tribute of Southern Shelf",
    "CharClass_CraterFemale":                                                    "Enemy: Bailly, Tribute of Sawtooth Cauldron",
    "CharClass_CraterMale":                                                      "Enemy: Moretus, Tribute of Sawtooth Cauldron",
    "CharClass_IncineratorFemale":                                               "Enemy: Cynder, Tribute of Frostburn",
    "CharClass_IncineratorMale":                                                 "Enemy: Fuse, Tribute of Frostburn",
    "CharClass_Lynchwood_Female":                                                "Enemy: Annie, Tribute of Lynchwood",
    "CharClass_Lynchwood_Male":                                                  "Enemy: Garret, Tribute of Lynchwood",
    "CharClass_RaiderFemale":                                                    "Enemy: Fiona, Tribute of Sanctuary",
    "CharClass_RaiderMale":                                                      "Enemy: Max, Tribute of Sanctuary",
    "CharClass_Snowman":                                                         "Enemy: Tinder Snowflake",
    "CharClass_GoliathGroom":                                                    "Enemy: Colin Zaford",
    "CharClass_GoliathBride":                                                    "Enemy: Bridget Hodunk",
    "CharClass_BlingLoader":                                                     "Enemy: BLNG Loader",
    "CharClass_Nast_Girl_Loader":                                                "Enemy: Stella (Rotgut)",
    "CharClass_Nast_BadassJunkLoader":                                           "Enemy: Ed (Rotgut)",
    "CharClass_Innuendobot_NPC":                                                 "Enemy: Innuendobot 5000",
    "CharClass_Nast_ThresherSigmund":                                            "Enemy: Sigmand",
    "CharClass_Nast_ThresherIkaroa":                                             "Enemy: Ikaroa",
    "CharClass_Nast_ThresherMoby":                                               "Enemy: Moby",
    "PawnBalance_Nast_ThresherPurple":                                           "Enemy: Fire Crak'n",
    "CharClass_Nast_ThresherLove":                                               "Enemy: Rue, the Love Thresher",
    "PawnBalance_Crawmerax_Son":                                                 "Enemy: Son of Crawmerax",
    "PawnBalance_Crawmerax_Son_Raid":                                            "Enemy: Son of Crawmerax Raid Boss",
    "CharClass_FlyntSon":                                                        "Enemy: Sparky Flynt",
    "CharClass_Orchid_Pirate_NoBeard":                                           "Enemy: No Beard",
    "CharClass_Orchid_StalkerPet":                                               "Enemy: Tinkles",
    "CharClass_Orchid_Grendel":                                                  "Enemy: Grendel",
    "CharClass_Orchid_MarauderMaster":                                           "Enemy: Sandman",
    "CharClass_Orchid_BigSleep":                                                 "Enemy: Big Sleep",
    "CharClass_Orchid_Deserter_Cook":                                            "Enemy: Benny the Booster",
    "CharClass_Orchid_Deserter_Deckhand":                                        "Enemy: Deckhand",
    "CharClass_Orchid_Deserter_Terry":                                           "Enemy: Toothless Terry",
    "CharClass_Orchid_Pervbot":                                                  "Enemy: P3RV-E",
    "CharClass_Orchid_LoaderBoss":                                               "Enemy: H3RL-E",
    "CharClass_Orchid_PirateRadioGuy":                                           "Enemy: DJ Tanner",
    "CharClass_MrBubbles":                                                       "Enemy: Mr. Bubbles",
    # "CharClass_Orchid_LittleSis":                                                "Enemy: Lil' Sis",
    "CharClass_Orchid_PirateHenchman2":                                          "Enemy: Lieutenant Hoffman (Pirate)",
    "CharClass_Orchid_PirateHenchman":                                           "Enemy: Lieutenant White (Pirate)",
    "CharacterClass_RakkHive":                                                   "Enemy: Roscoe",
    # "CharacterClass_Orchid_BossWorm":                                            "Enemy: The Leviathan", # doesn't trigger
    "CharClass_Orchid_RaidEngineer":                                             "Enemy: Hyperius",
    "CharClass_Orchid_RaidShaman":                                               "Enemy: Master Gee",
    "CharClass_Iris_Pyro_Pete":                                                  "Enemy: Pyro Pete",
    "CharClass_Iris_SullyStabber":                                               "Enemy: Sully the Stabber",
    "CharClass_Iris_Hamhock":                                                    "Enemy: Hamhock",
    "CharClass_Iris_BuffGamer":                                                  "Enemy: Buff Gamer",
    "CharClass_Iris_GameCritic":                                                 "Enemy: Game Critic",
    "CharClass_Iris_MotorMama":                                                  "Enemy: Motor Mama",
    "CharClass_Iris_SayFaceTroll":                                               "Enemy: Anonymous Troll",
    "CharClass_Iris_Uriah":                                                      "Enemy: Uriah",
    "CharClass_Iris_BlimpBoss":                                                  "Enemy: Piston's Blimp",
    "CharClass_Truckasaurus":                                                    "Enemy: Badassasaurus",
    "CharClass_Iris_Piston_Boss":                                                "Enemy: Piston",
    "CharClass_Iris_Raid_PyroPete":                                              "Enemy: Pyro Pete the Invincible",
    "CharClass_DrifterNamed":                                                    "Enemy: Arizona",
    "CharClass_Sage_Ep3_Creature":                                               "Enemy: Thermitage",
    "CharClass_Sage_DahliaMurder_Creature":                                      "Enemy: Rakkanoth",
    "CharClass_Sage_FollowGlow_Creature":                                        "Enemy: Dribbles",
    "CharClass_Sage_Ep4_Creature":                                               "Enemy: Woundspike",
    "CharClass_Sage_PallingAround_Creature":                                     "Enemy: The Bulwark",
    "CharClass_Sage_BigFeet_Creature":                                           "Enemy: Rouge",
    "CharClass_Sage_NowYouSeeIt_Creature":                                       "Enemy: Bloodtail",
    "CharClass_Sage_FinalBoss":                                                  "Enemy: Jackenstein",
    "CharClass_Sage_DrNakayama":                                                 "Enemy: Dr. Nakayama",
    "CharClass_Sage_AcquiredTaste_Creature":                                     "Enemy: Bulstoss",
    "CharClass_BoneyPants":                                                      "Enemy: Mr. Boney Pants Guy",
    "CharClass_Golem_SwordInStone":                                              "Enemy: Unmotivated Golem",
    "CharClass_SirReginald":                                                     "Enemy: Sir Reginald von Bartlesby",
    "CharClass_Spiderpants":                                                     "Enemy: Spiderpants",
    "CharClass_Orc_Butcher":                                                     "Enemy: Arguk the Butcher",
    "CharClass_Orc_WarlordNamed2":                                               "Enemy: Warlord Grug",
    "CharClass_Knight_LostSoulsInv_Proto2":                                      "Enemy: -=n00bkiller=-",
    "CharClass_Knight_MMO1_Proto":                                               "Enemy: 420_E-Sports_Masta",
    "CharClass_Knight_MMO2_Proto":                                               "Enemy: [720NoScope]Headshotz",
    "CharClass_Knight_MMO3_Proto":                                               "Enemy: xxDatVaultHuntrxx",
    "PawnBalance_SkeletonKing_Aliah":                                            "Enemy: King Aliah",
    "PawnBalance_SkeletonKing_Crono":                                            "Enemy: King Crono",
    "PawnBalance_SkeletonKing_Seth":                                             "Enemy: King Seth",
    "PawnBalance_SkeletonKing_Nazar":                                            "Enemy: King Nazar",
    "PawnBalance_GolemFlying_Maxibillion":                                       "Enemy: Maxibillion",
    "CharClass_Orc_ClaptrapWand_Proto":                                          "Enemy: Magical Orc",
    "CharClass_Spider_ClaptrapWand_Proto":                                       "Enemy: Magical Spider",
    "CharClass_GolemGold":                                                       "Enemy: Gold Golem",
    "CharClass_WinterKnight_Canine":                                             "Enemy: Canine",
    "CharClass_WinterKnight_Molehill":                                           "Enemy: Molehill",
    "CharClass_SirBoil":                                                         "Enemy: Sir Boil",
    "CharClass_SirMash":                                                         "Enemy: Sir Mash",
    "CharClass_SirStew":                                                         "Enemy: Sir Stew",
    "CharClass_DragonBridgeBoss":                                                "Enemy: Handsome Dragon",
    "CharClass_AngelBoss":                                                       "Enemy: Sorcerer's Daughter",
    "CharClass_Wizard_DeadBrotherEdgar_Proto2":                                  "Enemy: Edgar/Simon",
    "CharClass_Wizard_DeadBrotherSimon_Proto2":                                  "Enemy: Edgar/Simon",
    "PawnBalance_JackWarlock_Demon":                                             "Enemy: Handsome Sorcerer",
    "CharClass_DragonRed_Raid":                                                  "Enemy: Incinerator",
    "CharClass_DragonBlue_Raid":                                                 "Enemy: Healianth",
    "CharClass_DragonGreen_Raid":                                                "Enemy: Brood",
    "CharClass_DragonPurple_Raid":                                               "Enemy: Boost",
    "CharClass_Orc_WarlordNamed3":                                               "Enemy: Warlord Turge",
    "CharClass_Orc_WarlordNamed1":                                               "Enemy: Warlord Slog",
    "CharClass_Anemone_Skag_Ghost":                                              "Enemy: Ghost",
    "CharClass_Anemone_TheDarkWeb":                                              "Enemy: The Dark Web",
    "CharClass_Anemone_UranusBOT":                                               "Enemy: Uranus Bot",
    "CharClass_Anemone_Lt_Angvar":                                               "Enemy: Lt. Angvar (New Pandora)",
    "CharClass_Anemone_Lt_Bolson":                                               "Enemy: Lt. Bolson (New Pandora)",
    "CharClass_Anemone_Lt_Tetra":                                                "Enemy: Lt. Tetra (New Pandora)",
    "CharClass_Anemone_Lt_Hoffman":                                              "Enemy: Lt. Hoffman (New Pandora)",
    "CharClass_Anemone_Cassius":                                                 "Enemy: Cassius",
    "CharClass_Anemone_Hector":                                                  "Enemy: Hector",
    "CharClass_DrifterRaid":                                                     "Enemy: Dexiduous the Invincible",
    "PawnBalance_Native_Badass": { 3:                                            "Enemy: Omnd-Omnd-Ohk" }, # unrealsdk.find_enum("EAITransformed")["EAIT_Corrosive"] == 3
    "PawnBalance_Nast_Native_Badass": { 3:                                       "Enemy: Omnd-Omnd-Ohk" },
    "CharClass_Sage_Raid_BeastMaster":                                           "Enemy: Chief Ngwatu",
    "CharClass_Sage_Raid_Beast":                                                 "Enemy: Voracidous the Invincible",
    "CharacterClass_Anemone_SandWormBoss_1":                                     "Enemy: Haderax the Invincible",
    "PawnBalance_BugMorphUltimateBadass": { 4:                                   "Enemy: Vermivorous the Invincible" }, # Supreme Badass Pod # unrealsdk.find_enum("EAITransformed")["EAIT_Custom"] == 4
    "PawnBalance_BugMorphRaid":                                                  "Enemy: Vermivorous the Invincible",
}

generic_enemy_lookup = {
    "skag":                                                                      "Generic: Skag",
    "rakk":                                                                      "Generic: Rakk",
    "primalbeast":                                                               "Generic: Bullymong",
    "psycho":                                                                    "Generic: Psycho",
    "_rat":                                                                      "Generic: Rat",
    "spiderant":                                                                 "Generic: Spiderant",
    "bugmorph":                                                                  "Generic: Varkid",
    "goliath":                                                                   "Generic: Goliath",
    "marauder":                                                                  "Generic: Marauder",
    "stalker":                                                                   "Generic: Stalker",
    "midget":                                                                    "Generic: Midget",
    "nomad":                                                                     "Generic: Nomad",
    "thresher":                                                                  "Generic: Thresher",
    "skeleton":                                                                  "Generic: Skeleton",
    "loader":                                                                    "Generic: Loader",
    "crystalisk":                                                                "Generic: Crystalisk",
    "probe":                                                                     "Generic: Surveyor",
    "gd_population_engineer":                                                    "Generic: Hyperion Personnel",
    "gd_population_constructor":                                                 "Generic: Constructor",
    "gd_population_gyrocopter":                                                  "Generic: Buzzard",
    "pirate":                                                                    "Generic: Pirate",
    "sandworm":                                                                  "Generic: Sand Worm",
    "bike":                                                                      "Generic: Biker",
    "iris_pawnbalance_gyrocopter":                                               "Generic: Flyboy Buzzard",
    "iris_pawnbalance_loader":                                                   "Generic: Torgue Loader",
    "rhino":                                                                     "Generic: Borok",
    "pawnbalance_native":                                                        "Generic: Savage",
    "pawnbalance_witchdoctor":                                                   "Generic: Witch Doctor",
    "drifter":                                                                   "Generic: Drifter",
    "scaylion":                                                                  "Generic: Scaylion",
    "spore":                                                                     "Generic: Spore",
    "gd_aster_pop_golems":                                                       "Generic: Golem",
    "gd_aster_pop_spiders":                                                      "Generic: Spider",
    "gd_aster_pop_treant":                                                       "Generic: Treant",
    "gd_aster_pop_wisp":                                                         "Generic: Pixie",
    "gd_aster_pop_orcs":                                                         "Generic: Orc",
    "gd_aster_pop_knights":                                                      "Generic: Knight",
    "gd_aster_pop_dragons":                                                      "Generic: Dragon",
    "pawnbalance_mimic":                                                         "Generic: Mimic",
    "gd_aster_pop_dwarves":                                                      "Generic: Dwarf",
    "gd_aster_pop_wizards":                                                      "Generic: Spellcaster",
    "pawnbalance_infected":                                                      "Generic: Infected",
    "gd_anemone_pop_np":                                                         "Generic: New Pandora Unit",
    "pumpkin":                                                                   "Generic: Pump-Kin",
    "kitchen":                                                                   "Generic: Chef",
    "butcher":                                                                   "Generic: Chef",
    "gd_allium_gameshowcam":                                                     "Generic: TorgueVision",
    "pawnbalance_bugmorph_bee":                                                  "Generic: Stabber Jabber",
    "yeti":                                                                      "Generic: Yeti",
    "gd_snow":                                                                   "Generic: Snowman",
    "_crab":                                                                     "Generic: Crab-Kin",
}