# These use the nicely formatted names
# TODO: potentially only need one per entrance. Not sure if they are all the right way round though
from BouncyLootGod.state import get_globals

entrance_to_req_areas = {
    # LevelTravelStationDefinition
    "BackburnerToOldDust":                     ["Dahl Abandon", "The Backburner"],
    # "BackburnerToSanctIntro":                [], #["The Backburner", "FFS Intro Sanctuary"],
    "HeliosToSandwormCavern":                  ["Helios Fallen", "The Burrows"],
    "OldDustToBackburner":                     ["The Backburner", "Dahl Abandon"],
    "OldDustToResearchCenter":                 ["Dahl Abandon", "Mt. Scarab Research Center"],
    "OldDustToSandwormCavern":                 ["Dahl Abandon", "The Burrows"],
    "RaidBossToSandwormCavern":                ["Writhing Deep"],
    "ResearchCenterToOldDust":                 ["Dahl Abandon", "Mt. Scarab Research Center"],
    "ResearchCenterToSanctuary":               ["Mt. Scarab Research Center"],
    # "SanctIntroToBackburner":                [], # ["FFS Intro Sanctuary", "The Backburner"],
    "SanctuaryToResearchCenter":               ["FFS Boss Fight"],
    "SandwormCavernToHelios":                  ["The Burrows", "Helios Fallen"],
    "SandwormCavernToOldDust":                 ["Dahl Abandon", "The Burrows"],
    "SandwormCavernToRaidBoss":                ["Writhing Deep", "The Burrows"],
    # "CastleExteriorToCastleKeepFake":        ["Hatred's Shadow", "Dragon Keep"],
    "CastleExteriorToDungeon":                 ["Lair of Infinite Agony", "Hatred's Shadow"],
    # "CastleExteriorToDungeons":              ["Hatred's Shadow", "Lair of Infinite Agony"],
    "CastleExteriorToMines":                   ["Hatred's Shadow", "Mines of Avarice"],
    # "CastleKeepToCastleExteriorFake":        ["Hatred's Shadow", "Dragon Keep"],
    "CastleKeepToDungeon":                     ["Dragon Keep", "Lair of Infinite Agony"],
    # "CastleKeepToDungeons":                  ["Dragon Keep", "Lair of Infinite Agony"],
    "DarkForestToDeadForest":                  ["The Forest", "Immortal Woods"],
    # "DarkForestToMines":                     ["The Forest", "Mines of Avarice"],
    "DarkForestToVillage":                     ["The Forest", "Flamerock Refuge"],
    "DeadForestToDarkForest":                  ["Immortal Woods", "The Forest"],
    "DeadForestToMines":                       ["Mines of Avarice", "Immortal Woods"],
    "DocksToVillage":                          ["Flamerock Refuge", "Unassuming Docks"],
    "DungeonRaidToDungeon":                    ["The Winged Storm"],
    # "DungeonRaidToDungeons":                 ["Lair of Infinite Agony", "The Winged Storm"],
    # "DungeonsToCastleExterior":              ["Hatred's Shadow", "Lair of Infinite Agony"],
    # "DungeonsToCastleKeep":                  ["Lair of Infinite Agony", "Dragon Keep"],
    # "DungeonsToDungeonRaid":                 ["Lair of Infinite Agony", "The Winged Storm"],
    "DungeonToCastleExterior":                 ["Lair of Infinite Agony"],
    "DungeonToCastleKeep":                     ["Dragon Keep", "Lair of Infinite Agony"],
    "DungeonToDungeonRaid":                    ["The Winged Storm", "Lair of Infinite Agony"],
    "MinesToCastleExterior":                   ["Mines of Avarice", "Hatred's Shadow"],
    # "MinesToDarkForest":                     ["The Forest", "Mines of Avarice"],
    "MinesToDeadForest":                       ["Immortal Woods", "Mines of Avarice"],
    "TempleOfSlaughterToVillage":              ["Murderlin's Temple"],
    "VillageToDarkForest":                     ["The Forest", "Flamerock Refuge"],
    "VillageToDocks":                          ["Flamerock Refuge", "Unassuming Docks"],
    # "VillageToMines":                        ["Flamerock Refuge", "Mines of Avarice"],
    "VillageToTempleOfSlaughter":              ["Murderlin's Temple", "Flamerock Refuge"],
    "BeatdowntoPyroPeats":                     ["Pyro Pete's Bar", "The Beatdown"],
    "BeatdowntoPyroPetes2":                    ["Pyro Pete's Bar", "The Beatdown"],
    # "CraterToKickedOut":                     [],
    "ArenaTASToCrater":                        ["Torgue Arena"],
    "ArenaToCrater":                           ["Torgue Arena"],
    "BackdoorToCrater":                        ["Torgue Arena"],
    "BeatdownToCrater":                        ["The Beatdown", "Badass Crater"],
    "ForgeToCrater":                           ["The Forge", "Badass Crater"],
    "CraterToArena":                           ["Torgue Arena", "Badass Crater"],
    "CraterToArenaTAS":                        ["Torgue Arena", "Badass Crater"],
    "CraterToBackdoor":                        ["Torgue Arena", "Badass Crater"],
    "CraterToBeatdown":                        ["The Beatdown", "Badass Crater"],
    "CraterToForge":                           ["The Forge", "Badass Crater"],
    "CraterToMamma":                           ["Southern Raceway", "Badass Crater"],
    "CraterToMoxxi":                           ["Badass Crater", "Badass Crater Bar"],
    "MammaToCrater":                           ["Badass Crater", "Southern Raceway"],
    "MoxxiToCrater":                           ["Badass Crater Bar", "Badass Crater"],
    # "KickedOutToCrater":                     ["Badass Crater"],
    "PyroPetesToBeatdown":                     ["Pyro Pete's Bar"],
    # "PyroPetesToBeatdown2":                  ["Pyro Pete's Bar", "The Beatdown"],
    "PyroPeteToBeatdown":                      ["Pyro Pete's Bar", "The Beatdown"],
    "PyroPetetoBeatdown2":                     ["Pyro Pete's Bar", "The Beatdown"],
    "AridNexusToStockade":                     ["Arid Nexus Badlands", "Arid Nexus Boneyard"],
    "AshToVolcano":                            ["Vault of the Warrior", "Eridium Blight"],
    "FrostToIce":                              ["Three Horns Divide", "Three Horns Valley"],
    "FrostToIce2":                             ["Three Horns Divide", "Three Horns Valley"],
    "GrassRoadToOutwash":                      ["Highlands Outwash", "Highlands"],
    "IcetoFrost":                              ["Three Horns Valley", "Three Horns Divide"],
    "IceToFrost2":                             ["Three Horns Valley", "Three Horns Divide"],
    "HypInterToInterlude":                     ["Friendship Gulag"],
    "InterludeToAsh":                          ["Eridium Blight", "The Dust"],
    # "InterludeToDamTop":                     ["The Dust", "Bloodshot Ramparts"], # !?
    # "InterludeToDLC":                        ["The Dust"], # ???
    "InterludeToGrass":                        ["Highlands", "The Dust"],
    "InterludeToHypInter":                     ["Friendship Gulag", "The Dust"],
    "InterludeToIce":                          ["The Dust", "Three Horns Valley"],
    "InterludeToLynchwood":                    ["Lynchwood", "The Dust"],
    "LynchwoodToInterlude":                    ["The Dust", "Lynchwood"],
    "OutwashToFridge":                         ["Highlands Outwash", "The Fridge"],
    "OutwashToGrass":                          ["Highlands", "Highlands Outwash"],
    "OutwashToGrassRoad":                      ["Highlands", "Highlands Outwash"],
    "StockadeToAridNexus":                     ["Arid Nexus Boneyard", "Arid Nexus Badlands"],
    "TundraExpressToWilhelm":                  ["End of the Line", "Tundra Express"],
    # "VolcanoToAsh":                          ["Eridium Blight", "Vault of the Warrior"],
    "WilhelmToTundraExpress":                  ["End of the Line"],
    "CavernsToSanctuaryHole":                  ["Caustic Caverns", "Sanctuary Hole"],
    "CoveToWaterfront":                        ["Southern Shelf Bay"],
    "DamToDamTop":                             ["Bloodshot Ramparts", "Bloodshot Stronghold"],
    "DamToIce":                                ["Three Horns Valley", "Bloodshot Stronghold"],
    "DamTopToDam":                             ["Bloodshot Ramparts"],
    # "DamTopToInterlude":                     ["Bloodshot Ramparts", "The Dust"], # ???
    "GlacialToWaterfront":                     ["Windshear Waste", "Southern Shelf"],
    "IceCanyonToIce":                          ["Three Horns Divide", "Frostburn Canyon"],
    "IceToDam":                                ["Bloodshot Stronghold", "Three Horns Valley"],
    "IceToFridge":                             ["The Fridge", "Three Horns Valley"],
    "IceToIceCanyon":                          ["Frostburn Canyon", "Three Horns Divide"],
    "IceToInterlude":                          ["The Dust", "Three Horns Valley"],
    "IceToSanctuary":                          ["Sanctuary", "Three Horns Divide"],
    "IceToSanctuaryHole":                      ["Sanctuary Hole", "Three Horns Divide"],
    "IceToSouthpawFactory":                    ["Southpaw Steam & Power", "Three Horns Valley"],
    "IceToTundraExpress":                      ["Tundra Express", "Three Horns Divide"],
    "IceToWaterfront":                         ["Three Horns Divide", "Southern Shelf"],
    "SanctuaryHoleToCaverns":                  ["Caustic Caverns", "Sanctuary Hole"],
    "SanctuaryHoleToIce":                      ["Sanctuary Hole"],
    "SanctuaryToIce":                          ["Sanctuary", "Three Horns Divide"],
    # "SanctuaryToVOGsChamber":                ["Sanctuary"],
    "SouthpawFactoryToIce":                    ["Southpaw Steam & Power", "Three Horns Valley"],
    "TundraExpressToIce":                      ["Tundra Express", "Three Horns Divide"],
    # "WaterfrontDocksToIce":                  ["Southern Shelf", "Three Horns Divide"],
    "WaterfrontToCove":                        ["Southern Shelf", "Southern Shelf Bay"],
    "WaterfrontToGlacial":                     ["Southern Shelf"],
    "WaterfrontToIce":                         ["Three Horns Divide", "Southern Shelf"],
    "BanditSlaughterToFridge":                 ["Fink's Slaughterhouse"],
    "BossCliffsToCliffs":                      ["The Bunker", "Thousand Cuts"],
    "BossCliffsToVOGsChamber":                 ["Control Core Angel", "The Bunker"],
    "CliffsToBossCliffs":                      ["Thousand Cuts", "The Bunker"],
    "CliffsToGrass":                           ["Thousand Cuts", "Highlands"],
    "CliffsToThresherRaid":                    ["Terramorphous Peak", "Thousand Cuts"],
    "CreatureSlaughterToPandoraPark":          ["Natural Selection Annex"],
    "FridgeToBanditSlaughter":                 ["Fink's Slaughterhouse", "The Fridge"],
    "FridgeToGrass":                           ["Highlands", "The Fridge"],
    "FridgeToIce":                             ["The Fridge", "Three Horns Valley"],
    "GrassToCliffs":                           ["Thousand Cuts", "Highlands"],
    "GrassToFridge":                           ["Highlands", "The Fridge"], # this isn't real?
    "GrassToHyperionCity":                     ["Opportunity", "Highlands"],
    "GrassToInterlude":                        ["The Dust", "Highlands"],
    "GrassToLuckys":                           ["The Holy Spirits", "Highlands"],
    "GrassToPandoraPark":                      ["Wildlife Exploitation Preserve", "Highlands"],
    "HyperionCityToGrass":                     ["Highlands", "Opportunity"],
    "LuckysToGrass":                           ["The Holy Spirits"],
    "PandoraParkToCreatureSlaughter":          ["Natural Selection Annex", "Wildlife Exploitation Preserve"],
    "PandoraParkToGrass":                      ["Wildlife Exploitation Preserve", "Highlands"],
    "ThresherRaidToCliffs":                    ["Terramorphous Peak"],
    "VOGsChamberToBossCliffs":                 ["Control Core Angel"],
    # "VOGsChamberToSanctuary":                ["Control Core Angel"],
    "AshToCraterLake":                         ["Sawtooth Cauldron", "Eridium Blight"],
    "AshToFinalBossAscent":                    ["Hero's Pass", "Eridium Blight"],
    "AshToFyrestone":                          ["Arid Nexus Boneyard", "Eridium Blight"],
    "AshToInterlude":                          ["The Dust", "Eridium Blight"],
    "AshToRobotSlaughter":                     ["Ore Chasm", "Eridium Blight"],
    "CraterLakeToAsh":                         ["Eridium Blight", "Sawtooth Cauldron"],
    "FinalBossAscentToAsh":                    ["Eridium Blight", "Hero's Pass"],
    "FinalBossAscentToVolcano":                ["Vault of the Warrior", "Hero's Pass"],
    "FyrestoneToAsh":                          ["Eridium Blight", "Arid Nexus Boneyard"],
    "RobotSlaughterToAsh":                     ["Ore Chasm"],
    "VolcanoToFinalBossAscent":                ["Vault of the Warrior"],
    "CavesToOasisTown":                        ["Oasis", "Hayter's Folly"],
    "OasisTownToCaves":                        ["Hayter's Folly", "Oasis"],
    "OasisTownToSaltFlats":                    ["Oasis", "Wurmwater"],
    # "OasisTownToSpire":                      ["Oasis", "Magnys Lighthouse"],
    "OasisTownToWormBelly":                    ["Oasis", "The Leviathan's Lair"],
    "RefineryToSaltFlats":                     ["Wurmwater", "Washburne Refinery"],
    "SaltFlatsToOasisTown":                    ["Oasis", "Wurmwater"],
    "SaltFlatsToRefinery":                     ["Washburne Refinery", "Wurmwater"],
    "SaltFlatsToShipGraveyard":                ["The Rustyards", "Wurmwater"],
    "SaltFlatsToSpire":                        ["Magnys Lighthouse", "Wurmwater"],
    # "SaltFlatsToWormBelly":                  ["Wurmwater", "The Leviathan's Lair"],
    "ShipGraveyardToSaltFlats":                ["Wurmwater", "The Rustyards"],
    # "SpireToOasisTown":                      ["Oasis", "Magnys Lighthouse"],
    "SpireToSaltFlats":                        ["Wurmwater", "Magnys Lighthouse"],
    "WormBellyToOasisTown":                    ["The Leviathan's Lair", "Oasis"],
    "WormBellyToSaltFlats":                    ["The Leviathan's Lair"],
    # "CliffsToUnderground":                   ["Candlerakk's Cragg", "Hunter's Grotto"],
    # "PowerStationToUnderground":             ["Ardorton Station", "Hunter's Grotto"],
    "Sage_Travel_CliffsToShip":                ["Terminus", "Candlerakk's Cragg"],
    "Sage_Travel_CliffsToUnderground":         ["Candlerakk's Cragg", "Hunter's Grotto"],
    "Sage_Travel_PowerStationToRockForest":    ["Ardorton Station", "Scylla's Grove"],
    "Sage_Travel_PowerStationToUnderground":   ["Hunter's Grotto", "Ardorton Station"],
    "Sage_Travel_RockForestToPowerStation":    ["Scylla's Grove", "Ardorton Station"],
    "Sage_Travel_RockForestToUnderground":     ["Hunter's Grotto", "Scylla's Grove"],
    # "Sage_Travel_RockForestToVillage":       ["Scylla's Grove", "Hunter's Grotto"], # ??
    "Sage_Travel_ShipToCliffs":                ["Terminus"],
    "Sage_Travel_UndergroundToCliffs":         ["Hunter's Grotto", "Candlerakk's Cragg"],
    "Sage_Travel_UndergroundToPowerStation":   ["Ardorton Station", "Hunter's Grotto"],
    "Sage_Travel_UndergroundToRockForest":     ["Scylla's Grove", "Hunter's Grotto"],

    # FastTravelStationDefinition
    "Hunger":                        ["Gluttony Gulch"],
    "Xmas":                          ["Marcus's Mercenary Shop"],
    "BackburnerIntro":               ["The Backburner"],
    "BackBurner":                    ["The Backburner"],
    "Helios":                        ["Helios Fallen"],
    "OldDust":                       ["Dahl Abandon"],
    "ResearchCenter":                ["Mt. Scarab Research Center"],
    "Helios_OneWay":                 ["Helios Fallen"],
    "ResearchCenter_OneWay":         ["Mt. Scarab Research Center"],
    "SanctuaryIntro":                ["FFS Intro Sanctuary"],
    "Sandworm_OneWay":               ["The Burrows"],
    "CastleExterior":                ["Hatred's Shadow"],
    "CastleKeep":                    ["Dragon Keep"],
    "DarkForest":                    ["The Forest"],
    "DeadForest":                    ["Immortal Woods"],
    "Docks":                         ["Unassuming Docks"],
    "Dungeons":                      ["Lair of Infinite Agony"],
    "Mines":                         ["Mines of Avarice"],
    "Village":                       ["Flamerock Refuge"],
    "FyrestoneOneWay":               ["Arid Nexus Badlands"],
    "Interlude":                     ["The Dust"],
    "Lynchwood":                     ["Lynchwood"],
    "Outwash":                       ["Highlands Outwash"],
    "Sanctuary":                     ["Sanctuary"],
    "Wilhelm":                       ["End of the Line"],
    "Caverns":                       ["Caustic Caverns"],
    "DamTop":                        ["Bloodshot Ramparts"],
    "Glacial":                       ["Windshear Waste"],
    "GlacialIgloo":                  ["Windshear Waste"],
    "GoshDam":                       ["Bloodshot Stronghold"],
    "IceCanyon":                     ["Frostburn Canyon"],
    "IceEast":                       ["Three Horns Divide"],
    "IceWest":                       ["Three Horns Valley"],
    "SouthernShelfTown":             ["Southern Shelf"],
    "SouthpawFactory":               ["Southpaw Steam & Power"],
    "TundraExpress":                 ["Tundra Express"],
    "TundraExpressSecret":           ["Tundra Express"],
    "TundraTrain":                   ["End of the Line"],
    "Cliffs":                        ["Thousand Cuts"],
    "Cliffs_Boss":                   ["The Bunker"],
    "Grass_A":                       ["Highlands"],
    "Grass_B":                       ["Highlands"],
    "Grass_C":                       ["Highlands"],
    "HyperionCity":                  ["Opportunity"],
    "PandoraPark":                   ["Wildlife Exploitation Preserve"],
    "TheFridge":                     ["The Fridge"],
    "Ash":                           ["Eridium Blight"],
    "CraterLake":                    ["Sawtooth Cauldron"],
    "FinalBossAscent":               ["Hero's Pass"],
    "OnFireStone":                   ["Arid Nexus Boneyard"],
    "Volcano_Boss_A":                ["Vault of the Warrior"],
    "Volcano_Boss_B":                ["Vault of the Warrior"],
    "PumpkinPatch":                  ["Hallowed Hollow"],
    "BadassBar":                     ["Badass Crater Bar"],
    "Beatdown":                      ["The Beatdown"],
    "Forge":                         ["The Forge"],
    "IrisCrater":                    ["Badass Crater"],
    "SouthernRaceway":               ["Southern Raceway"],
    "TestingZone":                   ["Digistruct Peak"],
    "EasterTravel":                  ["Wam Bam Island"],
    "Vday":                          ["Rotgut Distillery"],
    "Caves":                         ["Hayter's Folly"],
    "OasisTown":                     ["Oasis"],
    "Refinary":                      ["Washburne Refinery"],
    "SaltFlats":                     ["Wurmwater"],
    "ShipGraveyard":                 ["The Rustyards"],
    "Spire":                         ["Magnys Lighthouse"],
    "TopOfSpire":                    ["Magnys Lighthouse"],
    "HyperionShip":                  ["Terminus"],
    "PowerStation":                  ["Ardorton Station"],
    "RockForest":                    ["Scylla's Grove"],
    "SageCliffs":                    ["Candlerakk's Cragg"],
    "Underground":                   ["Hunter's Grotto"],
    "Underground_Lodge":             ["Hunter's Grotto"],
}

travel_targets = {
     "Windshear Waste":                    "GD_FastTravelStations.Zone1.GlacialIgloo",
     "Windshear Start":                    "GD_FastTravelStations.Zone1.Glacial",
     "Southern Shelf":                     "GD_LevelTravelStations.Zone1.WaterfrontToGlacial",
     "Southern Shelf Bay":                 "GD_LevelTravelStations.Zone1.CoveToWaterfront",
     "Three Horns Divide":                 "GD_FastTravelStations.Zone1.IceEast",
     "Sanctuary":                          "GD_FastTravelStations.Sanctuary.Sanctuary",
     "Frostburn Canyon":                   "GD_FastTravelStations.Zone1.IceCanyon",
     "Three Horns Valley":                 "GD_FastTravelStations.Zone1.IceWest",
     "Southpaw Steam & Power":             "GD_FastTravelStations.Zone1.SouthpawFactory",
     "The Dust":                           "GD_FastTravelStations.Interlude.Interlude",
     "Bloodshot Stronghold":               "GD_FastTravelStations.Zone1.GoshDam",
     "Bloodshot Ramparts":                 "GD_LevelTravelStations.Zone1.DamTopToDam",
     "Friendship Gulag":                   "GD_LevelTravelStations.Interlude.HypInterToInterlude",
     "Tundra Express":                     "GD_FastTravelStations.Zone1.TundraExpress",
     "End of the Line":                    "GD_LevelTravelStations.WilhelmToTundraExpress",
     "The Fridge":                         "GD_FastTravelStations.Zone2.TheFridge",
     "Fink's Slaughterhouse":              "GD_LevelTravelStations.Zone2.BanditSlaughterToFridge",
     "Highlands Outwash":                  "GD_FastTravelStations.Outwash",
     "Highlands":                          "GD_FastTravelStations.Zone2.Grass_A",
     "The Holy Spirits":                   "GD_LevelTravelStations.Zone2.LuckysToGrass",
     "Sanctuary Hole":                     "GD_LevelTravelStations.Zone1.SanctuaryHoleToIce",
     "Caustic Caverns":                    "GD_FastTravelStations.Zone1.Caverns",
     "Wildlife Exploitation Preserve":     "GD_FastTravelStations.Zone2.PandoraPark",
     "Natural Selection Annex":            "GD_LevelTravelStations.Zone2.CreatureSlaughterToPandoraPark",
     "Thousand Cuts":                      "GD_FastTravelStations.Zone2.Cliffs",
     "Lynchwood":                          "GD_FastTravelStations.Interlude.Lynchwood",
     "Opportunity":                        "GD_FastTravelStations.Zone2.HyperionCity",
     "The Bunker":                         "GD_FastTravelStations.Zone2.Cliffs_Boss",
     "Control Core Angel":                 "GD_LevelTravelStations.Zone2.VOGsChamberToBossCliffs",
     "Eridium Blight":                     "GD_FastTravelStations.Zone3.Ash",
     "Ore Chasm":                          "GD_LevelTravelStations.Zone3.RobotSlaughterToAsh",
     "Sawtooth Cauldron":                  "GD_FastTravelStations.Zone3.CraterLake",
     "Arid Nexus Boneyard":                "GD_FastTravelStations.Zone3.OnFireStone",
     "Arid Nexus Badlands":                "GD_FastTravelStations.FyrestoneOneWay",
     "Hero's Pass":                        "GD_FastTravelStations.Zone3.FinalBossAscent",
     "Vault of the Warrior":               "GD_LevelTravelStations.Zone3.VolcanoToFinalBossAscent",
     "Terramorphous Peak":                 "GD_LevelTravelStations.Zone2.ThresherRaidToCliffs",
     "FFS Intro Sanctuary":                "GD_Anemone_FastTravel.SanctuaryIntro",
     "The Backburner":                     "GD_Anemone_FastTravel.FastTravelStations.BackBurner",
     "Dahl Abandon":                       "GD_Anemone_FastTravel.FastTravelStations.OldDust",
     "The Burrows":                        "GD_Anemone_FastTravel.Sandworm_OneWay",
     "Helios Fallen":                      "GD_Anemone_FastTravel.FastTravelStations.Helios",
     "Mt. Scarab Research Center":         "GD_Anemone_FastTravel.FastTravelStations.ResearchCenter",
     "FFS Boss Fight":                     "GD_Anemone_LevelTravel.SanctuaryToResearchCenter",
     "Writhing Deep":                      "GD_Anemone_LevelTravel.RaidBossToSandwormCavern",
     "Unassuming Docks":                   "GD_Aster_FastTravel.Docks",
     "Flamerock Refuge":                   "GD_Aster_FastTravel.Village",
     "The Forest":                         "GD_Aster_FastTravel.DarkForest",
     "Immortal Woods":                     "GD_Aster_FastTravel.DeadForest",
     "Hatred's Shadow":                    "GD_Aster_FastTravel.CastleExterior",
     "Mines of Avarice":                   "GD_Aster_FastTravel.Mines",
     "Lair of Infinite Agony":             "GD_Aster_LevelTravel.DungeonToCastleExterior",
     "Dragon Keep":                        "GD_Aster_FastTravel.CastleKeep",
     "Murderlin's Temple":                 "GD_Aster_LevelTravel.TempleOfSlaughterToVillage",
     "The Winged Storm":                   "GD_Aster_LevelTravel.DungeonRaidToDungeon",
     "Badass Crater":                      "GD_Iris_FastTravelStations.Hub.IrisCrater",
     "Torgue Arena":                       "GD_Iris_LevelTravelStations.Dogleg1.ArenaToCrater",
     "The Beatdown":                       "GD_Iris_FastTravelStations.Beatdown",
     "Pyro Pete's Bar":                    "GD_Iris_LevelTravelStations.PyroPetesToBeatdown",
     "Badass Crater Bar":                  "GD_Iris_FastTravelStations.BadassBar",
     "Torgue Arena Ring":                  "GD_Iris_LevelTravelStations.Dogleg1.BackdoorToCrater", # special case
     "Southern Raceway":                   "GD_Iris_FastTravelStations.SouthernRaceway",
     "The Forge":                          "GD_Iris_FastTravelStations.Forge",
     "Torgue Arena TAS":                   "GD_Iris_LevelTravelStations.Dogleg1.ArenaTASToCrater", # special case
     "Oasis":                              "GD_Orchid_FastTravel.OasisTown.OasisTown",
     "Wurmwater":                          "GD_Orchid_FastTravel.SaltFlats.SaltFlats",
     "Hayter's Folly":                     "GD_Orchid_FastTravel.Caves",
     "The Rustyards":                      "GD_Orchid_FastTravel.ShipGraveyard",
     "Washburne Refinery":                 "GD_Orchid_FastTravel.Refinary",
     "Magnys Lighthouse":                  "GD_Orchid_FastTravel.Spire",
     "The Leviathan's Lair":               "GD_Orchid_LevelTravel.WormBelly.WormBellyToSaltFlats",
     "Hunter's Grotto":                    "GD_Sage_FastTravel.Underground",
     "Hunter's Grotto Lodge":              "GD_Sage_FastTravel.Underground_Lodge",
     "Scylla's Grove":                     "GD_Sage_FastTravel.RockForest",
     "Ardorton Station":                   "GD_Sage_FastTravel.PowerStation",
     "Candlerakk's Cragg":                 "GD_Sage_FastTravel.SageCliffs",
     "Terminus":                           "GD_Sage_LevelTravel.Sage_Travel_ShipToCliffs",
     "Digistruct Peak":                    "GD_Lobelia_FastTravel.TestingZone",
     "Hallowed Hollow":                    "GD_Flax_FastTravel.PumpkinPatch",
     "Gluttony Gulch":                     "GD_Allium_FastTravel.Hunger",
     "Marcus's Mercenary Shop":            "GD_Allium_FastTravel.Xmas",
     "Rotgut Distillery":                  "GD_Nasturtium_FastTravel.Vday",
     "Wam Bam Island":                     "GD_Nasturtium_FastTravel.EasterTravel",
}

region_requirement_exceptions = {
    "Windshear Start":              "Windshear Waste",
    "Torgue Arena TAS":             "Torgue Arena",
    "Torgue Arena Ring":            "Torgue Arena",
    "Hunter's Grotto Lodge":        "Hunter's Grotto",
}

region_translation_dict = {
    "windshearwaste":                  "Windshear Waste",
    "windshear":                       "Windshear Waste",
    "waste":                           "Windshear Waste",
    "claptrapsplace":                  "Windshear Waste",
    "claptrap":                        "Windshear Waste",
    "igloo":                           "Windshear Waste",
    "ww":                              "Windshear Waste",
    "windshearstart":                  "Windshear Start",
    "beginning":                       "Windshear Start",
    "start":                           "Windshear Start",
    "aridnexusboneyard":               "Arid Nexus Boneyard",
    "boneyard":                        "Arid Nexus Boneyard",
    "anbo":                            "Arid Nexus Boneyard",
    "theholyspirits":                  "The Holy Spirits",
    "holyspirits":                     "The Holy Spirits",
    "holy":                            "The Holy Spirits",
    "spirits":                         "The Holy Spirits",
    "luckys":                          "The Holy Spirits",
    "ths":                             "The Holy Spirits",
    "southpawsteampower":              "Southpaw Steam & Power",
    "southpaw":                        "Southpaw Steam & Power",
    "steam":                           "Southpaw Steam & Power",
    "power":                           "Southpaw Steam & Power",
    "ssap":                            "Southpaw Steam & Power",
    "ssp":                             "Southpaw Steam & Power",
    "sanctuaryhole":                   "Sanctuary Hole",
    "sh":                              "Sanctuary Hole",
    "hole":                            "Sanctuary Hole",
    "herospass":                       "Hero's Pass",
    "heros":                           "Hero's Pass",
    "hero":                            "Hero's Pass",
    "hp":                              "Hero's Pass",
    "bloodshotstronghold":             "Bloodshot Stronghold",
    "bloodshot":                       "Bloodshot Stronghold",
    "stronghold":                      "Bloodshot Stronghold",
    "bs":                              "Bloodshot Stronghold",
    "bss":                             "Bloodshot Stronghold",
    "threehornsvalley":                "Three Horns Valley",
    "threehorns":                      "Three Horns Valley",
    "valley":                          "Three Horns Valley",
    "thv":                             "Three Horns Valley",
    "sanctuary":                       "Sanctuary",
    "sanc":                            "Sanctuary",
    "s":                               "Sanctuary",
    "thousandcuts":                    "Thousand Cuts",
    "thousand":                        "Thousand Cuts",
    "brick":                           "Thousand Cuts",
    "cuts":                            "Thousand Cuts",
    "tc":                              "Thousand Cuts",
    "endoftheline":                    "End of the Line",
    "eotl":                            "End of the Line",
    "wilhelm":                         "End of the Line",
    "wildlifeexploitationpreserve":    "Wildlife Exploitation Preserve",
    "wildlife":                        "Wildlife Exploitation Preserve",
    "preserve":                        "Wildlife Exploitation Preserve",
    "wildlifepreserve":                "Wildlife Exploitation Preserve",
    "wep":                             "Wildlife Exploitation Preserve",
    "terramorphouspeak":               "Terramorphous Peak",
    "terramorphous":                   "Terramorphous Peak",
    "terra":                           "Terramorphous Peak",
    "tp":                              "Terramorphous Peak",
    "tundra":                          "Tundra Express",
    "tundraexpress":                   "Tundra Express",
    "te":                              "Tundra Express",
    "thefridge":                       "The Fridge",
    "fridge":                          "The Fridge",
    "finksslaughterhouse":             "Fink's Slaughterhouse",
    "finks":                           "Fink's Slaughterhouse",
    "fsh":                             "Fink's Slaughterhouse",
    "southernshelfbay":                "Southern Shelf Bay",
    "shelfbay":                        "Southern Shelf Bay",
    "ssb":                             "Southern Shelf Bay",
    "bay":                             "Southern Shelf Bay",
    "frostburncanyon":                 "Frostburn Canyon",
    "frostburn":                       "Frostburn Canyon",
    "canyon":                          "Frostburn Canyon",
    "fc":                              "Frostburn Canyon",
    "fbc":                             "Frostburn Canyon",
    "threehornsdivide":                "Three Horns Divide",
    "divide":                          "Three Horns Divide",
    "thd":                             "Three Horns Divide",
    "highlands":                       "Highlands",
    "highland":                        "Highlands",
    "thehighlands":                    "Highlands",
    "thehighland":                     "Highlands",
    "thl":                             "Highlands",
    "hl":                              "Highlands",
    "high":                            "Highlands",
    "naturalselectionannex":           "Natural Selection Annex",
    "natural":                         "Natural Selection Annex",
    "nsa":                             "Natural Selection Annex",
    "annex":                           "Natural Selection Annex",
    "thedust":                         "The Dust",
    "dust":                            "The Dust",
    "td":                              "The Dust",
    "friendshipgulag":                 "Friendship Gulag",
    "friendship":                      "Friendship Gulag",
    "gulag":                           "Friendship Gulag",
    "fg":                              "Friendship Gulag",
    "opportunity":                     "Opportunity",
    "bloodshotramparts":               "Bloodshot Ramparts",
    "ramparts":                        "Bloodshot Ramparts",
    "br":                              "Bloodshot Ramparts",
    "bsr":                             "Bloodshot Ramparts",
    "aridnexusbadlands":               "Arid Nexus Badlands",
    "badlands":                        "Arid Nexus Badlands",
    "anba":                            "Arid Nexus Badlands",
    "ss":                              "Southern Shelf",
    "southernshelf":                   "Southern Shelf",
    "shelf":                           "Southern Shelf",
    "highlandsoutwash":                "Highlands Outwash",
    "outwash":                         "Highlands Outwash",
    "thlo":                            "Highlands Outwash",
    "hlo":                             "Highlands Outwash",
    "causticcaverns":                  "Caustic Caverns",
    "caustic":                         "Caustic Caverns",
    "caverns":                         "Caustic Caverns",
    "lynchwood":                       "Lynchwood",
    "l":                               "Lynchwood",
    "sawtoothcauldron":                "Sawtooth Cauldron",
    "sawtooth":                        "Sawtooth Cauldron",
    "sc":                              "Sawtooth Cauldron",
    "cauldron":                        "Sawtooth Cauldron",
    "orechasm":                        "Ore Chasm",
    "ore":                             "Ore Chasm",
    "chasm":                           "Ore Chasm",
    "oc":                              "Ore Chasm",
    "thebunker":                       "The Bunker",
    "bunker":                          "The Bunker",
    "controlcoreangel":                "Control Core Angel",
    "controlcore":                     "Control Core Angel",
    "control":                         "Control Core Angel",
    "angel":                           "Control Core Angel",
    "cca":                             "Control Core Angel",
    "vaultofthewarrior":               "Vault of the Warrior",
    "warrior":                         "Vault of the Warrior",
    "vault":                           "Vault of the Warrior",
    "votw":                            "Vault of the Warrior",
    "eridiumblight":                   "Eridium Blight",
    "eb":                              "Eridium Blight",
    "eridium":                         "Eridium Blight",
    "blight":                          "Eridium Blight",
    "ash":                             "Eridium Blight",
    "gluttonygulch":                   "Gluttony Gulch",
    "gluttony":                        "Gluttony Gulch",
    "glutton":                         "Gluttony Gulch",
    "gulch":                           "Gluttony Gulch",
    "gg":                              "Gluttony Gulch",
    "marcussmercenaryshop":            "Marcus's Mercenary Shop",
    "marcusmercenaryshop":             "Marcus's Mercenary Shop",
    "marcus":                          "Marcus's Mercenary Shop",
    "mercenary":                       "Marcus's Mercenary Shop",
    "mercenaryday":                    "Marcus's Mercenary Shop",
    "xmas":                            "Marcus's Mercenary Shop",
    "christmas":                       "Marcus's Mercenary Shop",
    "mms":                             "Marcus's Mercenary Shop",
    "heliosfallen":                    "Helios Fallen",
    "helios":                          "Helios Fallen",
    "ffsbossfight":                    "FFS Boss Fight",
    "ffsboss":                         "FFS Boss Fight",
    "hector":                          "FFS Boss Fight",
    "paradisesanctum":                 "FFS Boss Fight",
    "paradise":                        "FFS Boss Fight",
    "sanctum":                         "FFS Boss Fight",
    "thebackburner":                   "The Backburner",
    "backburner":                      "The Backburner",
    "tba":                             "The Backburner",
    "ffsintrosanctuary":               "FFS Intro Sanctuary",
    "ffs":                             "FFS Intro Sanctuary",
    "ffsintro":                        "FFS Intro Sanctuary",
    "dahlabandon":                     "Dahl Abandon",
    "da":                              "Dahl Abandon",
    "dahl":                            "Dahl Abandon",
    "abandon":                         "Dahl Abandon",
    "mtscarabresearchcenter":          "Mt. Scarab Research Center",
    "mtscarabresearch":                "Mt. Scarab Research Center",
    "mtscarab":                        "Mt. Scarab Research Center",
    "scarab":                          "Mt. Scarab Research Center",
    "msrc":                            "Mt. Scarab Research Center",
    "msrf":                            "Mt. Scarab Research Center",
    "researchcenter":                  "Mt. Scarab Research Center",
    "research":                        "Mt. Scarab Research Center",
    "theburrows":                      "The Burrows",
    "burrows":                         "The Burrows",
    "tbu":                             "The Burrows",
    "writhingdeep":                    "Writhing Deep",
    "writhing":                        "Writhing Deep",
    "wd":                              "Writhing Deep",
    "theforest":                       "The Forest",
    "forest":                          "The Forest",
    "immortalwoods":                   "Immortal Woods",
    "immortal":                        "Immortal Woods",
    "iw":                              "Immortal Woods",
    "dragonkeep":                      "Dragon Keep",
    "dragon":                          "Dragon Keep",
    "keep":                            "Dragon Keep",
    "dk":                              "Dragon Keep",
    "unassumingdocks":                 "Unassuming Docks",
    "docks":                           "Unassuming Docks",
    "unassuming":                      "Unassuming Docks",
    "ud":                              "Unassuming Docks",
    "flamerockrefuge":                 "Flamerock Refuge",
    "flamerock":                       "Flamerock Refuge",
    "refuge":                          "Flamerock Refuge",
    "fr":                              "Flamerock Refuge",
    "hatredsshadow":                   "Hatred's Shadow",
    "hatredshadow":                    "Hatred's Shadow",
    "hatred":                          "Hatred's Shadow",
    "hatreds":                         "Hatred's Shadow",
    "shadow":                          "Hatred's Shadow",
    "hs":                              "Hatred's Shadow",
    "lairofinfiniteagony":             "Lair of Infinite Agony",
    "lairofinfinite":                  "Lair of Infinite Agony",
    "lair":                            "Lair of Infinite Agony",
    "agony":                           "Lair of Infinite Agony",
    "infiniteagony":                   "Lair of Infinite Agony",
    "loia":                            "Lair of Infinite Agony",
    "murderlinstemple":                "Murderlin's Temple",
    "murderlin":                       "Murderlin's Temple",
    "murderlins":                      "Murderlin's Temple",
    "murder":                          "Murderlin's Temple",
    "mt":                              "Murderlin's Temple",
    "minesofavarice":                  "Mines of Avarice",
    "moa":                             "Mines of Avarice",
    "mines":                           "Mines of Avarice",
    "avarice":                         "Mines of Avarice",
    "thewingedstorm":                  "The Winged Storm",
    "wingedstorm":                     "The Winged Storm",
    "winged":                          "The Winged Storm",
    "storm":                           "The Winged Storm",
    "tws":                             "The Winged Storm",
    "ws":                              "The Winged Storm",
    "hallowedhollow":                  "Hallowed Hollow",
    "hallowed":                        "Hallowed Hollow",
    "hollow":                          "Hallowed Hollow",
    "hallow":                          "Hallowed Hollow",
    "hallow":                          "Hallowed Hollow",
    "halloween":                       "Hallowed Hollow",
    "hh":                              "Hallowed Hollow",
    "torguearena":                     "Torgue Arena",
    "arena":                           "Torgue Arena",
    "ta":                              "Torgue Arena",
    "torguearenatas":                  "Torgue Arena TAS",
    "arenatas":                        "Torgue Arena TAS",
    "torguefinalarena":                "Torgue Arena TAS",
    "torguearenafinal":                "Torgue Arena TAS",
    "finalarena":                      "Torgue Arena TAS",
    "arenafinal":                      "Torgue Arena TAS",
    "torguearenaring":                 "Torgue Arena Ring",
    "arenaring":                       "Torgue Arena Ring",
    "thebeatdown":                     "The Beatdown",
    "beatdown":                        "The Beatdown",
    "theforge":                        "The Forge",
    "forge":                           "The Forge",
    "badasscrater":                    "Badass Crater",
    "badass":                          "Badass Crater",
    "crater":                          "Badass Crater",
    "bc":                              "Badass Crater",
    "southernraceway":                 "Southern Raceway",
    "raceway":                         "Southern Raceway",
    "sr":                              "Southern Raceway",
    "pyropetesbar":                    "Pyro Pete's Bar",
    "pyropete":                        "Pyro Pete's Bar",
    "pyropetes":                       "Pyro Pete's Bar",
    "pyropetebar":                     "Pyro Pete's Bar",
    "petesbar":                        "Pyro Pete's Bar",
    "petebar":                         "Pyro Pete's Bar",
    "pete":                            "Pyro Pete's Bar",
    "pyro":                            "Pyro Pete's Bar",
    "ppb":                             "Pyro Pete's Bar",
    "badasscraterbar":                 "Badass Crater Bar",
    "badassbar":                       "Badass Crater Bar",
    "moxxisbar":                       "Badass Crater Bar",
    "moxxibar":                        "Badass Crater Bar",
    "moxxibar":                        "Badass Crater Bar",
    "craterbar":                       "Badass Crater Bar",
    "bar":                             "Badass Crater Bar",
    "bcb":                             "Badass Crater Bar",
    "digistructpeak":                  "Digistruct Peak",
    "digistruct":                      "Digistruct Peak",
    "digipeak":                        "Digistruct Peak",
    "digi":                            "Digistruct Peak",
    "dp":                              "Digistruct Peak",    
    "wambamisland":                    "Wam Bam Island",
    "wambam":                          "Wam Bam Island",
    "easter":                          "Wam Bam Island",
    "wb":                              "Wam Bam Island",
    "wbi":                             "Wam Bam Island",
    "rotgutdistillery":                "Rotgut Distillery",
    "rotgut":                          "Rotgut Distillery",
    "distillery":                      "Rotgut Distillery",
    "vday":                            "Rotgut Distillery",
    "rot":                             "Rotgut Distillery",
    "rg":                              "Rotgut Distillery",
    "rgd":                             "Rotgut Distillery",
    "rd":                              "Rotgut Distillery",
    "theleviathanslair":               "The Leviathan's Lair",
    "leviathanslair":                  "The Leviathan's Lair",
    "leviathanlair":                   "The Leviathan's Lair",
    "leviathans":                      "The Leviathan's Lair",
    "leviathan":                       "The Leviathan's Lair",
    "ll":                              "The Leviathan's Lair",
    "levi":                            "The Leviathan's Lair",
    "washburnerefinery":               "Washburne Refinery",
    "washburnrefinery":                "Washburne Refinery",
    "refinery":                        "Washburne Refinery",
    "washburne":                       "Washburne Refinery",
    "washburn":                        "Washburne Refinery",
    "wr":                              "Washburne Refinery",
    "wurmwater":                       "Wurmwater",
    "wurm":                            "Wurmwater",
    "w":                               "Wurmwater",
    "magnyslighthouse":                "Magnys Lighthouse",
    "magnys":                          "Magnys Lighthouse",
    "lighthouse":                      "Magnys Lighthouse",
    "ml":                              "Magnys Lighthouse",
    "therustyards":                    "The Rustyards",
    "rustyards":                       "The Rustyards",
    "rust":                            "The Rustyards",
    "tr":                              "The Rustyards",
    "haytersfolly":                    "Hayter's Folly",
    "hayters":                         "Hayter's Folly",
    "hayter":                          "Hayter's Folly",
    "folly":                           "Hayter's Folly",
    "hayterfolly":                     "Hayter's Folly",
    "oasis":                           "Oasis",
    "ardortonstation":                 "Ardorton Station",
    "ardorton":                        "Ardorton Station",
    "as":                              "Ardorton Station",
    "huntersgrotto":                   "Hunter's Grotto",
    "huntergrotto":                    "Hunter's Grotto",
    "hg":                              "Hunter's Grotto",
    "grotto":                          "Hunter's Grotto",
    "hunters":                         "Hunter's Grotto",
    "huntersgrottolodge":              "Hunter's Grotto Lodge",
    "huntergrottolodge":               "Hunter's Grotto Lodge",
    "hunterslodge":                    "Hunter's Grotto Lodge",
    "hunterlodge":                     "Hunter's Grotto Lodge",
    "grottolodge":                     "Hunter's Grotto Lodge",
    "lodge":                           "Hunter's Grotto Lodge",
    "candlerakkscragg":                "Candlerakk's Cragg",
    "candlerakks":                     "Candlerakk's Cragg",
    "candlerakk":                      "Candlerakk's Cragg",
    "cragg":                           "Candlerakk's Cragg",
    "terminus":                        "Terminus",
    "hssterminus":                     "Terminus",
    "t":                               "Terminus",
    "scyllasgrove":                    "Scylla's Grove",
    "scyllas":                         "Scylla's Grove",
    "scylla":                          "Scylla's Grove",
    "grove":                           "Scylla's Grove",
    "sg":                              "Scylla's Grove",
}

progressive_travel_lookup = {
    "basegame": [
        "Windshear Waste", # index 0 always available
        "Southern Shelf",
        "Three Horns Divide",
        "Sanctuary",
        "Frostburn Canyon",
        "Three Horns Valley",
        "The Dust",
        "Bloodshot Stronghold",
        "Bloodshot Ramparts",
        "Friendship Gulag",
        "Tundra Express",
        "End of the Line",
        "The Fridge",
        "Highlands Outwash",
        "Highlands",
        "Wildlife Exploitation Preserve",
        "Thousand Cuts",
        "Opportunity",
        "The Bunker",
        "Control Core Angel",
        "Eridium Blight",
        "Sawtooth Cauldron",
        "Arid Nexus Boneyard",
        "Arid Nexus Badlands",
        "Hero's Pass",
        "Vault of the Warrior",
    ],
    "basegame_side": [
        "",
        "Southern Shelf Bay",
        "Southpaw Steam & Power",
        "Fink's Slaughterhouse",
        "The Holy Spirits",
        "Sanctuary Hole",
        "Caustic Caverns",
        "Natural Selection Annex",
        "Lynchwood",
        "Ore Chasm",
        "Terramorphous Peak",
    ],
    "ffs": [
        "",
        "FFS Intro Sanctuary",
        "The Backburner",
        "Dahl Abandon",
        "The Burrows",
        "Helios Fallen",
        "Mt. Scarab Research Center",
        "FFS Boss Fight",
        "Writhing Deep",
    ],
    "tina": [
        "",
        "Unassuming Docks",
        "Flamerock Refuge",
        "The Forest",
        "Immortal Woods",
        "Mines of Avarice",
        "Hatred's Shadow",
        "Lair of Infinite Agony",
        "Dragon Keep",
        "Murderlin's Temple",
        "The Winged Storm",
    ],
    "torgue": [
        "",
        "Badass Crater",
        "Torgue Arena",
        "The Beatdown",
        "Pyro Pete's Bar",
        "Badass Crater Bar",
        "Southern Raceway",
        "The Forge",
    ],
    "scarlett": [
        "",
        "Oasis",
        "Wurmwater",
        "Hayter's Folly",
        "The Rustyards",
        "Washburne Refinery",
        "Magnys Lighthouse",
        "The Leviathan's Lair",
    ],
    "hammerlock": [
        "",
        "Hunter's Grotto",
        "Scylla's Grove",
        "Ardorton Station",
        "Candlerakk's Cragg",
        "Terminus",
    ],
    "headhunter": [
        "",
        "Hallowed Hollow",
        "Gluttony Gulch",
        "Marcus's Mercenary Shop",
        "Rotgut Distillery",
        "Wam Bam Island",
    ]
}

progressive_travel_items = {
    "basegame": "Progressive Travel: Base Game",
    "basegame_side": "Progressive Travel: Side Area",
    "ffs": "Progressive Travel: Fight For Sanctuary DLC",
    "tina": "Progressive Travel: Tina DLC",
    "torgue": "Progressive Travel: Torgue DLC",
    "scarlett": "Progressive Travel: Scarlett DLC",
    "hammerlock": "Progressive Travel: Hammerlock DLC",
    "headhunter": "Progressive Travel: Headhunters",
}
progressive_travel_groups = {v: k for k, v in progressive_travel_items.items()}